name: C++ Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y g++ make

    - name: Install GCC (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew install gcc

    - name: Install GCC (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw make
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

    - name: Build and Test Randomize
      run: make -C memory test-randomize

    - name: Build and Test Canary
      run: make -C memory test-canary

    - name: Build and Test SecureData
      run: make -C memory test-securedata

    - name: Build and Test SecureArray
      run: make -C memory test-securearray

    - name: Success Message
      run: echo "Build and tests passed on all platforms."
